import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import  {MantineProviderWrapper} from "@/components/mantine-provider";
import { QueryProvider } from "@/components/query-provider";
import { ConditionalHeader } from "../components/conditional-header";
const roboto = Roboto({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Salona App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <QueryProvider>
            <MantineProviderWrapper>
              <ConditionalHeader />
              {children}
            </MantineProviderWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
