import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import  {MantineProviderWrapper} from "@/components/mantine-provider";
import { Header } from "@/components/header";
import { QueryProvider } from "@/components/query-provider";
const roboto = Roboto({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Salona App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} antialiased`}>
        <QueryProvider>
          <MantineProviderWrapper>
            <Header />
            {children}
          </MantineProviderWrapper>
        </QueryProvider>
      </body>
    </html>
  );
}
